### ISSUE TITLE
Plan struct is missing several fields

### ISSUE THREAD

**Issue by YijinLiu** [chargebee/chargebee-go#1]
According to [https://apidocs.chargebee.com/docs/api/plans](https://apidocs.chargebee.com/docs/api/plans), there should be fields like PricingModel, Tiers, ApplicableAddons, etc.
PricingModel probably should be ChargeModel, which is missing values like Tiered, Value and Stairstep.
Looks like you intentionally omitted them. Any reason behind that?

**Comment by YijinLiu** [comment]
Hmm, I guess it's because this library is V1. Any plan to support V2? We are considering using Chargebee for our billing service. Information contained in these fields are required for us.

**Comment by SangeethaBaskaran** [comment]
@YijinLiu Please use our latest version which is 2.0.0 for PricingModel changes.
