### ISSUE TITLE
enum.ApplyOn and enum.DurationType are missing (stack trace provided)

### ISSUE THREAD

**Issue by gmatty** [chargebee/chargebee-go#24]
# github.com/chargebee/chargebee-go/models/invoice
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/invoice/invoice.go:448:19: undefined: enum.ApplyOn
# github.com/chargebee/chargebee-go/models/estimate
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/estimate/estimate.go:157:21: undefined: enum.ApplyOn
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/estimate/estimate.go:158:21: undefined: enum.DurationType
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/estimate/estimate.go:316:21: undefined: enum.ApplyOn
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/estimate/estimate.go:317:21: undefined: enum.DurationType
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/estimate/estimate.go:487:21: undefined: enum.ApplyOn
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/estimate/estimate.go:488:21: undefined: enum.DurationType
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/estimate/estimate.go:495:21: undefined: enum.OperationType
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/estimate/estimate.go:870:19: undefined: enum.ApplyOn
# github.com/chargebee/chargebee-go/models/quote
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/quote/quote.go:623:21: undefined: enum.ApplyOn
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/quote/quote.go:624:21: undefined: enum.DurationType
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/quote/quote.go:699:21: undefined: enum.ApplyOn
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/quote/quote.go:700:21: undefined: enum.DurationType
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/quote/quote.go:787:21: undefined: enum.ApplyOn
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/quote/quote.go:788:21: undefined: enum.DurationType
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/quote/quote.go:795:21: undefined: enum.OperationType
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/quote/quote.go:896:21: undefined: enum.ApplyOn
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/quote/quote.go:897:21: undefined: enum.DurationType
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/quote/quote.go:904:21: undefined: enum.OperationType
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/quote/quote.go:904:21: too many errors
# github.com/chargebee/chargebee-go/models/hostedpage
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/hostedpage/hosted_page.go:305:19: undefined: enum.ApplyOn
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/hostedpage/hosted_page.go:419:21: undefined: enum.ApplyOn
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/hostedpage/hosted_page.go:420:21: undefined: enum.DurationType
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/hostedpage/hosted_page.go:606:21: undefined: enum.ApplyOn
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/hostedpage/hosted_page.go:607:21: undefined: enum.DurationType
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/hostedpage/hosted_page.go:614:21: undefined: enum.OperationType
# github.com/chargebee/chargebee-go/models/subscription
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/subscription/subscription.go:558:21: undefined: enum.ApplyOn
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/subscription/subscription.go:559:21: undefined: enum.DurationType
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/subscription/subscription.go:859:21: undefined: enum.ApplyOn
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/subscription/subscription.go:860:21: undefined: enum.DurationType
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/subscription/subscription.go:867:21: undefined: enum.OperationType
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/subscription/subscription.go:1365:21: undefined: enum.ApplyOn
../../../../pkg/mod/github.com/chargebee/chargebee-go@v2.13.0+incompatible/models/subscription/subscription.go:1366:21: undefined: enum.DurationType

**Comment by cb-yateshmathuria** [comment]
@gmatty - we have released a patch version [v2.13.1](https://github.com/chargebee/chargebee-go/tree/v2.13.1) which solves this issue.

**Comment by cb-khushbubibay** [comment]
Closing this issue.

**Comment by gmatty** [comment]
Thanks!
