### ISSUE TITLE
current version installation (main) is broken

### ISSUE THREAD

**Issue by lopezator** [chargebee/chargebee-go#25]
You cannot normally execute a simple:

> go get github.com/chargebee/chargebee-go

Because it will fail with the following message:

> github.com/chargebee/chargebee-go-old/models/discount: cannot find module providing package github.com/chargebee/chargebee-go-old/models/discount

This is because of this import:

> "github.com/chargebee/chargebee-go-old/models/discount"

Here: 

https://github.com/chargebee/chargebee-go/blob/6888f52f2cfc16646eff437dacd8cc6542a1766b/result.go#L4

What is exactly `chargebee-go-old`? Is a private repository? 

If I remove the import and try to install again it works, but I am obviously lacking the `discount` package that it's being used here:

https://github.com/chargebee/chargebee-go/blob/6888f52f2cfc16646eff437dacd8cc6542a1766b/result.go#L68

**Comment by cb-yateshmathuria** [comment]
Fixed in [v2.14.1](https://github.com/chargebee/chargebee-go/tree/v2.14.1)

**Comment by lopezator** [comment]
> Fixed in [v2.14.1](https://github.com/chargebee/chargebee-go/tree/v2.14.1)

Thank you!
