### ISSUE TITLE
Custom field example is incorrect or incomplete

### ISSUE THREAD

**Issue by logingood** [chargebee/chargebee-go#27]
Hi there, 

[An example](https://github.com/chargebee/chargebee-go#create-a-subscription-with-custom-headers-and-custom-fields) of passing custom fields to the subscription seems incorrect or incomplete. For the subscription case it is incorrect. I haven't had a chance to try for customer.

Using the documented example I was trying to pass `subscription[cf_custom_internal_id]` with value `foo-123`. Unfortunately it did not work, however it worked right away when I used `cf_custom_internal_id` (without `subscription[]`). I suggest to clarify documentation about this and add extra details of usage of `AddParams` in the godoc comment above the method.

```go
  res, err := subscriptionAction.Create(&subscription.CreateRequestParams{
    PlanId: "cbdemo_grow",
  }).AddParams("cf_custom_internal_id","foo-123").Request() 
```

**Comment by cb-khushbubibay** [comment]
Hi @logingood 
Thanks for notifying us regarding that, We updated the README with the correct sample code for custom field in v2.16.0 and v3.1.0 version.
API Docs is also having sample code for this please refer the different create use cases: https://apidocs.chargebee.com/docs/api/subscriptions?prod_cat_ver=1&lang=dotnet#create-usecases

USE CASE NUMBER - 4 
/*
    creates a subscription with meta data and custom fields.
*/

using ChargeBee.Api;
using ChargeBee.Models;
ApiConfig.Configure("{site}","{site_api_key}");
EntityResult result = Subscription.Create()
		.PlanId("no_trial")
		.AutoCollection(AutoCollectionEnum.Off)
		.Param("cf_gender","Male")
		.MetaData(JObject.Parse("{'features':{'usage-limit':'5GB','speed-within-quota':'2MBbps','post-usage-quota':'512kbps'}}"))
		.Request();

Subscription subscription = result.Subscription;
Customer customer = result.Customer;
Card card = result.Card;
Invoice invoice = result.Invoice;
List<UnbilledCharge> unbilledCharges = result.UnbilledCharges;
