### ISSUE TITLE
`chargebee.WithHTTPClient` has no effect

### ISSUE THREAD

**Issue by xv-thomas-c** [chargebee/chargebee-go#29]
Hi Chargebee team,

I am using the v3 API and want to set a custom http client for testing.

I see that there's [this](https://github.com/chargebee/chargebee-go/blob/master/environment.go#L36) `chargbee.WithHTTPClient` exposed for configuring the HTTP client.
https://github.com/chargebee/chargebee-go/blob/5db10caf41f2115c308912054405f840313882a4/environment.go#L36-L41

However it seems the `httpClient` in `environment.go` is not used at all when making HTTP call

https://github.com/chargebee/chargebee-go/blob/5db10caf41f2115c308912054405f840313882a4/environment.go#L22

That the request code always creates a new `http.Client` for each request.

https://github.com/chargebee/chargebee-go/blob/5db10caf41f2115c308912054405f840313882a4/http_request.go#L13-L17

**Comment by irejanodev** [comment]
Hi, this [PR ](https://github.com/chargebee/chargebee-go/pull/32) should fix it.

**Comment by cb-khushbubibay** [comment]
Hi @xv-thomas-c 
We have fixed the issue for the custom http client in v3.2.0 and 2.17.0.
