### ISSUE TITLE
Allow to update a Subscription and not only its items

### ISSUE THREAD

**Issue by ethielc** [chargebee/chargebee-go#35]
Subscriptions can have custom fields, currently is not possible by API to update a subscription and add/edit custom fields to it

**Comment by cb-khushbubibay** [comment]
Hi @ethielc 
We do have a provision to add/edit custom fields value : Raised PR: https://github.com/chargebee/cb-client-libs/pull/175
But the creation of a new custom fields can be done only by UI.
