### ISSUE TITLE
Please make the librabry thread-safe

### ISSUE THREAD

**Issue by defectus** [chargebee/chargebee-go#4]
Currently you make use of global variables but they're prone to race conditions. 
It would be great if you could provide a way of avoiding them.

I need to use mutexes all over the place when talking to Chargebee just to not run into race conditions.

A good example is here: https://github.com/chargebee/chargebee-go/blob/master/util.go#L13
When making two simultaneous calls (running two goroutines) I get race condition there.

**Comment by pkopac** [comment]
@defectus I recommend forking the library, we ended up doing that:
https://github.com/chartmogul/chargebee-go
...speaking of which I need to merge latest into it.

Unfortunately, maintainer told me they don't have time for merging my fix PR, which forces me to maintain a fork, you're welcome to use it, too.

**Comment by montanaflynn** [comment]
Any official word on this from @SangeethaBaskaran and @cb-goutham?

**Comment by cb-khushbubibay** [comment]
Hi @defectus @montanaflynn  @pkopac 
This issue has been addressed in v2.13.0.
Request you to please use v2.13.0 or latest version of chargebee-go SDK.
