### ISSUE TITLE
Misplaced option for Configure

### ISSUE THREAD

**Issue by pavel-odintsov** [chargebee/chargebee-go#5]
Hello!

On documentation page (https://github.com/chargebee/chargebee-go) you have:
```
chargebee.Configure("{site}", "{site_api_key}")
```

But correct sequence is opposite: https://github.com/chargebee/chargebee-go/blob/5824781067507dd9542be5809be3d152398260d1/environment.go#L28

I tested it and only "key", "site" works fine. 

Thank you!

**Comment by cb-rakesh** [comment]
This has been fixed in v2.3.0
