### ISSUE TITLE
chargebee.DefaultHTTPTimeout not working ?

### ISSUE THREAD

**Issue by lachlanh** [chargebee/chargebee-go#8]
Hi, I am building an integration with chargebee, I set chargebee.DefaultHTTPTimeout (https://github.com/chargebee/chargebee-go/blob/master/environment.go#L17) in my test but it does not affect the timeout. 
Think this is because the httpClient here : https://github.com/chargebee/chargebee-go/blob/master/http_request.go#L10 is already evaluated ? which means setting the DefaultHTTPTimeout has no impact. 

Would it be possible to export the httpClient ?
Test looks mostly like this : 
```golang
chargebee.Configure(conf.APIKey, conf.Site)
chargebee.DefaultHTTPTimeout = 500 * time.Microsecond
response, err := subscriptionAction.Create(...).Request()
//expect a timeout error.. doesn't happen.
```

**Comment by cb-rakesh** [comment]
This has been fixed in v2.3.0
